name: Build
on:
  create:
    tags:
      - "*"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-10.14]
        emacs: [25.3, 26.3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Ensure Dependencies
        run: ./ensure_dependencies.sh

      - name: Build
        run: ./build_emacs.sh ${{ matrix.emacs }} ${{ matrix.os }}

      - name: Save Emacs.app
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: dist/Emacs-${{ matrix.os }}.dmg

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout for detect repositor
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: setup Go for use ghr
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
        id: go

      - name: Get ghr
        run: go get github.com/tcnksm/ghr

      - name: Get Artifacts
        uses: actions/download-artifact@master
        with:
          name: artifacts

      - name: Make Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
          echo $TAGNAME
          $HOME/go/bin/ghr $TAGNAME artifacts/
