name: "Build"
on:
  push:
    branches:
      - master
jobs:
  build:
    name: "Build"
    runs-on: macos-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@master

      - name: "Ensure Dependencies"
        run: ./ensure_dependencies.sh

      - name: "Build"
        run: ./build_emacs.sh 26.3

      - name: "Store Artifacts"
        with:
          name: Emacs.dmg
          path: $HOME/Emacs.dmg
